### ISSUE TITLE
getByRole does not work with "term"

### ISSUE THREAD

**Issue by supervanya** [testing-library/dom-testing-library#703]
- Testing Framework and version: 

```@testing-library/react: 10.4.4```
  
```jest: 24.9.0```
- DOM Environment:
  
```@testing-library/jest-dom: ^5.11.0```

### Relevant code or config:

```js
const dt = screen.getAllByRole("term");
```

### What you did:
I was trying to get `dt` elements by role ("term")

### What happened:

I am getting an error:
`Unable to find an accessible element with the role "term"`
(more info in the sandbox)

### Reproduction:
https://codesandbox.io/s/react-testing-library-demo-skxjh?file=/src/__tests__/hello.js

### Problem description:
`term` is one of the accessible roles as stated on w3 [here](https://www.w3.org/TR/html-aria/#document-conformance-requirements-for-use-of-aria-attributes-in-html#el-dt)
It used to work in the `@testing-library/react: 10.2.1` but broke in `10.3.0`

### Suggested solution:
I am a pretty new front end developer and unfortunately don't have a solution but I would really appreciate any help and I could possibly try to create a PR (never done this before though)

**Comment by timdeschryver** [comment]
#683  should fix this.

**Comment by timdeschryver** [comment]
Closed by #683 .
Could you try it out @supervanya ?

**Comment by alanhchoi** [comment]
It's still not working on 10.4.7 https://codesandbox.io/s/react-testing-library-demo-zmkvi?file=/src/__tests__/hello.js

**Comment by marcosvega91** [comment]
I have opened a PR on  https://github.com/A11yance/aria-query/pull/70

**Comment by timdeschryver** [comment]
Thanks @alanhchoi and @marcosvega91.

**Comment by eps1lon** [comment]
@all-contributors add @supervanya for bug
